nodejs_app_name: universal
nodejs_app_install_dir: /opt/gpii/node_modules/{{ nodejs_app_name }}
nodejs_app_git_repo: https://github.com/gpii/universal.git
nodejs_app_git_branch: master
nodejs_app_commands:
  - npm install
  - grunt dedupe-infusion
  - npm test
